### PR TITLE
Tutorial Read Links 404 - Issue

### PR DESCRIPTION
**Pull request by nicholasvuono**
File Path: out/_next/static/v1.4.0/pages/tutorials.js
Made the code fix for the issue I opened earlier.

### CODE REVIEW

**Comment by 255kb** [comment]
Thank you for the PR, however you shouldn't modify the NextJS build directly (`out` folder). 
Instead you have to modify this file: https://github.com/mockoon/website/blob/master/pages/tutorials.js and recompile the project with `npm run build` and then `npm run export`.

**Comment by 255kb** [comment]
Do you want to update your PR? I can also do the fix as I have another one to do (I will probably to this tonight)

**Comment by nicholasvuono** [comment]
Apologies, I'm not very familiar with NextJs but it makes sense to recompile after the modification. If you have another one to fix then by all means take it away especially if you already have it planned for tonight

**Comment by 255kb** [comment]
No problem, I will close this PR then. 
Thank you for your help anyway, it's much appreciated 👍

**Pull request closed without merging**
